services:
  php:
    # uncomment the following line if you want to use a custom Dockerfile
    build: .
    # uncomment the following line if you want to run this in a production environment
    # restart: always
    container_name: 'php'
    ports:
      - "${APP_PORT:-80}:80" # HTTP
      - "4430:443" # HTTPS
      #- "443:443/udp" # HTTP/3
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    # comment the following line in production, it allows to have nice human-readable logs in dev
    tty: true
    networks:
      - boilerplate-net

  pgsql:
    image: 'postgres:15'
    container_name: 'pgsql'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'boilerplate-data:/var/lib/postgresql/data'
    networks:
      - boilerplate-net

  redis:
    image: 'redis:alpine'
    container_name: 'redis'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'boilerplate-redis:/data'
    networks:
      - boilerplate-net

  minio:
    image: 'minio/minio:latest'
    container_name: 'minio'
    ports:
      - '${FORWARD_MINIO_PORT:-9000}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
    environment:
      MINIO_ROOT_USER: acme
      MINIO_ROOT_PASSWORD: password
    volumes:
      - 'boilerplate-minio:/data/minio'
    networks:
      - boilerplate-net
    command: 'minio server /data/minio --console-address ":8900"'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      retries: 3
      timeout: 5s

  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_SERVER: pgsql
    ports:
      - 8888:8080
    networks:
      - boilerplate-net

networks:
  boilerplate-net:

    # Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  boilerplate-data:
    driver: local
  boilerplate-redis:
    driver: local
  boilerplate-minio:
    driver: local
